baseurl: /drmips

# Custom variables
title: DrMIPS
tagline: Educational MIPS simulator
repourl: https://github.com/brunonova/drmips
cur_ver: v2.0.3
android:
  min_version: 4.0
author:
  username: brunonova
  name: Bruno Nova
